### PR TITLE
Added formula for git-together

### PR DESCRIPTION
**Pull request by ehrenmurdick**
git-together is an alternative to git-pair, written by a Alpha, a Seattle pivot. It's like duet, in that it uses the committer and author fields, and like pair in that you don't have to change you git usage habits.

### CODE REVIEW

**Comment by xinzweb** [comment]
Btw, do we need `allmark` in same PR as the `git-together`? I like `git-together` a lot and used it everyday. Thanks a lot for putting together such a wonderful tool.

**Comment by ehrenmurdick** [comment]
Oh, we don't need allmark at all. That was a mistake, I'll remove it from the PR right away.

**Comment by ehrenmurdick** [comment]
And all the thanks goes to @kejadlen , my only contribution was this PR 😄

**Comment by xinzweb** [comment]
Would you please fix the following issues? Well, you can ignore the `alpha` one.

```
xzhangs-Mac:greenplum-db xzhang$ brew audit --strict --online git-together
ehrenmurdick/tap/git-together:
  * C: 5: col 3: `url` (line 5) should be put before `version` (line 4)
  * Stable version URLs should not contain alpha
Error: 2 problems in 1 formula
```

**Pull request closed without merging**
