### PR TITLE
Remove bosh-init from pivotal tap

### PR DESCRIPTION
**Pull request by voelzmo**
bosh-init is now in the official CF tap at https://github.com/cloudfoundry/homebrew-tap

You might want to do the same with CF-cli, so there are not two taps to maintain.

### CODE REVIEW

**Comment by nebhale** [comment]
What is the plan for migrating everyone who is already using the formula from here?  By removing this, I believe they'll be left with their current version with no prompt that they need to change to another tap to get it.

**Comment by voelzmo** [comment]
Anybody actually using this tap had an outdated version for 4 months last year and for 3 months this year. I don't have any statistics, but it doesn't seem like users of this tap care about updates much.

So: there is no migration strategy, I don't know of a graceful way to do this in homebrew.

**Comment by gregturn** [comment]
Anybody thought of coordinating with Twitter @pivotal and @cloudfoundry accounts to at least put out the word? Maybe blog.pivotal.io?

**Comment by nebhale** [comment]
Thanks to an under-documented feature (`tap_migrations.json`) this is now complete and should be seamless for all users.  Resolved by https://github.com/pivotal/homebrew-tap/commit/657433469a129accd31e8924dc1e3a483d5fd350

**Comment by voelzmo** [comment]
Ha, nicely put "underdocumented" :)
Thanks!

**Pull request closed without merging**
