### PR TITLE
Update Spring Boot 1.3.4.RELEASE

### PR DESCRIPTION
**Pull request by snicoll**

### CODE REVIEW

**Comment by nebhale** [comment]
@snicoll Can you please update with a `sha256` hash instead of `sha1`.  The latter is deprecated and results in warnings when installed.

**Comment by snicoll** [comment]
Wow, why has that changed now? It's the content [straight from the repo](http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.3.4.RELEASE/spring-boot-cli-1.3.4.RELEASE-homebrew.rb) so I need to figure out why it was changed.

ping @wilkinsona

**Comment by wilkinsona** [comment]
Looks like a breakdown in communication. The change to `sha256` was [made here](https://github.com/pivotal/homebrew-tap/commit/3a1a3bbd3ba238e17e626b2d672d212364200476). Boot's own script needs to be updated.

**Comment by snicoll** [comment]
@nebhale I've updated the PR

**Pull request merged**
